### PR TITLE
Don't add frame if user cancels.

### LINKED ISSUE #388: Cancelling the insertion of a frame breaks the UI
Tested against HEAD (98f955c):

* Open a dashboard
* Click on "Add frame"
* Press cancel
* Get a stacktrace in your terminal starting with: `Error: url is null`
* The newly created elements can't be interacted with.

broken promdash

### PR DESCRIPTION
**Pull request by stuartnelson3**
Previously, canceling would not abort adding a frame, which would break
the UI.

fixes #388

### CODE REVIEW

**Comment by grobie** [comment]
:+1: (while a test would have been nice :p)

File: spec/features/graph_spec.rb [hunk 1]
```diff
@@ -60,16 +60,23 @@
           open_tab 'Remove graph'
           click_button 'Delete'
           click_button 'Add Frame'
-          accept_alert
-          open_tab 'Remove frame'
+        end
+
+        it "should allow canceling on frame creation" do
+          dismiss_alert
```
Comment (stuartnelson3) [inline spec/features/graph_spec.rb]: @grobie
image

**Comment by juliusv** [comment]
Woot :+1:

File: spec/features/graph_spec.rb (hunk 1 above)
Comment (grobie) [inline spec/features/graph_spec.rb]: :dancers:
