### PR TITLE
correctly connect prometheus url and path in url generator

### LINKED ISSUE #450: Link to graph broken when using path in server URL
Noticed the `Datasources > Link to Graph in Prometheus` button link is broken if you use a path in the server url.

My server URL is `http://dash.example.com/prom/`
The link that button opens in a new tab is `http://dash.mapgets.com/promgraph#<fragment>`

It seems to strip the last fwd slash from the path + "graph". I dunno why without path it would work if it strips the first slash, that would become `http://dash.mapgets.comgraph#<fragment>` so there must be some special check for it.

### PR DESCRIPTION
**Pull request by stuartnelson3**
fixes #450 
@julius

### CODE REVIEW

**Comment by juliusv** [comment]
:+1:

File: app/assets/javascripts/angular/directives/expression.js.erb [hunk 1]
```diff
@@ -86,7 +86,7 @@ angular.module("Prometheus.directives").directive('expression', ["$http",
         }
 
         var expression = VariableInterpolator(scope.expr.expression, scope.vars);
-        var url = URLGenerator(server.url, "graph", scope.vars);
+        var url = URLGenerator(server.url, "/graph", scope.vars);
```
Comment (grobie) [inline app/assets/javascripts/angular/directives/expression.js.erb]: So, this change would not have been necessary actually?

Comment (stuartnelson3) [inline app/assets/javascripts/angular/directives/expression.js.erb]: Yes, totally unnecessary. It was added for consistency with the rest of the
project

Am Mittwoch, 23. September 2015 schrieb Tobias Schmidt :
